extends RefCounted

const DemoConstants = preload("res://scripts/core/demo_constants.gd")
const PersonalActionInstruction = preload("res://scripts/core/personal_action_instruction.gd")
const ActionValidator = preload("res://scripts/core/action_validator.gd")
const LogUtils = preload("res://scripts/core/log_utils.gd")

static func settle_turn(runtime: Dictionary, content: Dictionary, player_id := DemoConstants.LOCAL_PLAYER_ID) -> Dictionary:
	var room_state: Dictionary = runtime.get("room_state", {})
	var turn_id := int(room_state.get("current_turn_id", 1))
	var world_day := int(room_state.get("current_world_day", 1))
	var world_hour := int(room_state.get("current_world_hour", 0))
	var turn_config: Dictionary = room_state.get("turn_config", DemoConstants.default_turn_config())
	var turn_total_hours := DemoConstants.turn_total_hours(turn_config)
	var original_queue: Array = runtime.get("pending_player_decisions", {}).get(player_id, [])
	var validation := ActionValidator.validate_queue(runtime, content, player_id, original_queue)

	if not validation["ok"]:
		return _validation_failed_result(turn_id, world_day, world_hour, player_id, validation)

	var actual_queue := _actual_queue_for_settlement(original_queue, turn_total_hours)
	var actual_entries := []
	var remaining_hours := turn_total_hours

	for action in actual_queue:
		var planned_duration := int(action.get("planned_duration_hours", 0))
		var consumed_hours = min(planned_duration, remaining_hours)
		if consumed_hours <= 0:
			continue
		remaining_hours -= consumed_hours
		actual_entries.append({
			"instruction_id": action.get("instruction_id", "generated_rest"),
			"action_id": action.get("action_id", "rest_or_guard"),
			"planned_duration_hours": planned_duration,
			"actual_consumed_hours": consumed_hours,
			"status": "completed",
			"skip_or_interrupt_reason": ""
		})

	if remaining_hours > 0:
		actual_entries.append({
			"instruction_id": "unallocated_time_rest",
			"action_id": "rest_or_guard",
			"planned_duration_hours": remaining_hours,
			"actual_consumed_hours": remaining_hours,
			"status": "completed",
			"skip_or_interrupt_reason": "unallocated_time_filled_by_rest"
		})

	var next_world_hour := world_hour + turn_total_hours
	var next_world_day := world_day + int(turn_config.get("turn_duration_days", DemoConstants.DEFAULT_TURN_DURATION_DAYS))
	var next_turn_id := turn_id + 1
	var next_macro_period_id := DemoConstants.macro_period_for_world_day(next_world_day)
	var summary := {
		"turn_id": turn_id,
		"player_id": player_id,
		"planned_actions": _summarize_actions(original_queue),
		"actual_actions": actual_entries,
		"turn_total_hours": turn_total_hours,
		"consumed_hours": turn_total_hours,
		"skipped_actions": [],
		"interruptions": [],
		"notes": ["Phase A empty settlement path: no movement, events, resources, or sect AI resolved yet."]
	}

	var visible_logs := [
		LogUtils.visible("turn_settlement_started", "第 %d 回合开始结算。" % turn_id, turn_id, world_day, world_hour)
	]
	for entry in actual_entries:
		visible_logs.append(LogUtils.visible("action_result", "行动 %s 实际消耗 %d 小时。" % [entry["action_id"], entry["actual_consumed_hours"]], turn_id, world_day, world_hour))
	visible_logs.append(LogUtils.visible("turn_settlement_finished", "第 %d 回合结束，世界时间推进到第 %d 天。" % [turn_id, next_world_day], turn_id, next_world_day, next_world_hour))

	var package := {
		"package_id": "s1_turn_%03d_phase_a" % turn_id,
		"source_system": "S1_settlement_bus",
		"turn_id": turn_id,
		"world_seed": room_state.get("world_seed", DemoConstants.DEFAULT_WORLD_SEED),
		"state_deltas": {
			"room_state": {
				"current_turn_id": next_turn_id,
				"current_world_day": next_world_day,
				"current_world_hour": next_world_hour,
				"current_hour_tick": next_world_hour,
				"current_macro_period_id": next_macro_period_id,
				"current_phase": "turn_end",
				"settlement_status": "completed",
				"world_state_version_increment": 1
			},
			"clear_pending_player_decisions": [player_id],
			"player_lock_state": {
				"player_id": player_id,
				"lock_state": "unlocked"
			}
		},
		"visible_logs": visible_logs,
		"debug_logs": [
			LogUtils.debug("s1_package_created", "ResultPackage generated by Phase A settlement.", turn_id, next_world_hour, {"actual_entries": actual_entries.size()})
		],
		"resource_changes": [],
		"errors": [],
		"original_vs_actual_summary": summary
	}

	var replay := {
		"replay_id": "turn_%03d_seed_%s" % [turn_id, str(room_state.get("world_seed", DemoConstants.DEFAULT_WORLD_SEED))],
		"schema_version": DemoConstants.SCHEMA_VERSION,
		"content_version": DemoConstants.CONTENT_VERSION,
		"turn_id": turn_id,
		"rng_seed": room_state.get("world_seed", DemoConstants.DEFAULT_WORLD_SEED),
		"input_actions": original_queue,
		"result_packages": [package],
		"original_vs_actual_summary": summary,
		"state_before": {
			"current_turn_id": turn_id,
			"current_world_day": world_day,
			"current_world_hour": world_hour,
			"world_state_version": room_state.get("world_state_version", 0)
		},
		"state_after": {
			"current_turn_id": next_turn_id,
			"current_world_day": next_world_day,
			"current_world_hour": next_world_hour,
			"world_state_version": int(room_state.get("world_state_version", 0)) + 1
		}
	}

	return {
		"ok": true,
		"validation": validation,
		"packages": [package],
		"turn_replay": replay
	}

static func _validation_failed_result(turn_id: int, world_day: int, world_hour: int, player_id: String, validation: Dictionary) -> Dictionary:
	var package := {
		"package_id": "s1_turn_%03d_validation_failed" % turn_id,
		"source_system": "S1_settlement_bus",
		"turn_id": turn_id,
		"state_deltas": {
			"room_state": {
				"current_phase": "personal_action_planning",
				"settlement_status": "validation_failed"
			},
			"player_lock_state": {
				"player_id": player_id,
				"lock_state": "unlocked"
			}
		},
		"visible_logs": [
			LogUtils.visible("validation_failed", "锁定失败：行动预案没有通过硬校验。", turn_id, world_day, world_hour)
		],
		"debug_logs": [
			LogUtils.debug("validation_failed", "Action validation failed before settlement.", turn_id, world_hour, validation)
		],
		"errors": validation["errors"]
	}
	return {
		"ok": false,
		"validation": validation,
		"packages": [package],
		"turn_replay": {}
	}

static func _actual_queue_for_settlement(original_queue: Array, turn_total_hours: int) -> Array:
	if original_queue.is_empty():
		return [PersonalActionInstruction.make_rest(DemoConstants.LOCAL_CHARACTER_ID, 1, turn_total_hours)]
	return original_queue.duplicate(true)

static func _summarize_actions(actions: Array) -> Array:
	var summaries := []
	for action in actions:
		if typeof(action) != TYPE_DICTIONARY:
			continue
		summaries.append({
			"instruction_id": action.get("instruction_id", ""),
			"action_id": action.get("action_id", ""),
			"planned_duration_hours": int(action.get("planned_duration_hours", 0)),
			"status": action.get("status", "draft")
		})
	return summaries
