#!/usr/bin/env python3
"""Export canonical project docs for Notion or ChatGPT Library import."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


SECTION_TITLE = "## 当前 canonical 文档"
DEFAULT_OUTPUT = "outputs/canonical-docs-export"
MARKER_FILE = ".canonical-docs-export"


@dataclass(frozen=True)
class CanonicalDoc:
    order: int
    topic: str
    label: str
    href: str
    source_path: Path
    export_name: str
    sha256: str


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export canonical docs listed in docs/index.md into a flat import "
            "directory with README.md and manifest.json."
        )
    )
    parser.add_argument(
        "--index",
        default="docs/index.md",
        help="Canonical docs index path, relative to repo root. Default: docs/index.md",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Export directory, relative to repo root unless absolute. Default: {DEFAULT_OUTPUT}",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove an existing empty export directory or one previously generated by this script.",
    )
    return parser.parse_args()


def resolve_inside(base: Path, candidate: Path) -> Path:
    resolved_base = base.resolve()
    resolved_candidate = candidate.resolve()
    try:
        resolved_candidate.relative_to(resolved_base)
    except ValueError as exc:
        raise ValueError(f"Path escapes allowed base: {candidate}") from exc
    return resolved_candidate


def read_index_rows(index_path: Path) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    in_section = False
    row_re = re.compile(r"^\|\s*(?P<topic>[^|]+?)\s*\|\s*\[(?P<label>[^\]]+)\]\((?P<href>[^)]+)\)\s*\|$")

    for line in index_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("## "):
            in_section = stripped == SECTION_TITLE
            continue
        if not in_section:
            continue
        if stripped.startswith("## "):
            break
        if not stripped.startswith("|") or "---" in stripped:
            continue
        match = row_re.match(stripped)
        if match:
            rows.append((match.group("topic").strip(), match.group("label").strip(), match.group("href").strip()))

    if not rows:
        raise RuntimeError(f"No canonical doc rows found under {SECTION_TITLE} in {index_path}")
    return rows


def export_filename(order: int, href: str) -> str:
    rel = Path(href)
    stem = rel.with_suffix("").as_posix().replace("/", "__")
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "-", stem).strip("-")
    return f"{order:02d}_{safe}.md"


def load_canonical_docs(root: Path, index_path: Path) -> list[CanonicalDoc]:
    docs_dir = resolve_inside(root, index_path.parent)
    docs: list[CanonicalDoc] = []
    for order, (topic, label, href) in enumerate(read_index_rows(index_path), start=1):
        if "://" in href:
            raise ValueError(f"External links are not supported in canonical table: {href}")
        source_path = resolve_inside(root, docs_dir / href)
        if not source_path.is_file():
            raise FileNotFoundError(f"Canonical source not found: {source_path}")
        source_bytes = source_path.read_bytes()
        docs.append(
            CanonicalDoc(
                order=order,
                topic=topic,
                label=label,
                href=href,
                source_path=source_path,
                export_name=export_filename(order, href),
                sha256=hashlib.sha256(source_bytes).hexdigest(),
            )
        )
    return docs


def prepare_output(root: Path, output_arg: str, clean: bool) -> Path:
    output = Path(output_arg)
    if not output.is_absolute():
        output = root / output
    output = output.resolve()

    if clean:
        if output == root:
            raise ValueError("Refusing to clean repo root")
        if output.exists():
            marker = output / MARKER_FILE
            has_marker = marker.is_file()
            is_empty = output.is_dir() and not any(output.iterdir())
            if not has_marker and not is_empty:
                raise ValueError(f"Refusing to clean unmarked non-empty directory: {output}")
            shutil.rmtree(output)

    output.mkdir(parents=True, exist_ok=True)
    output.joinpath(MARKER_FILE).write_text("generated by scripts/export_canonical_docs.py\n", encoding="utf-8")
    return output


def yaml_value(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def exported_doc_content(doc: CanonicalDoc, root: Path, exported_at: str, index_rel: str) -> str:
    source_rel = doc.source_path.relative_to(root).as_posix()
    body = doc.source_path.read_text(encoding="utf-8").rstrip() + "\n"
    header = "\n".join(
        [
            "---",
            f"canonical_topic: {yaml_value(doc.topic)}",
            f"source_path: {yaml_value(source_rel)}",
            f"source_index: {yaml_value(index_rel)}",
            f"exported_at: {yaml_value(exported_at)}",
            "---",
            "",
        ]
    )
    return header + body


def write_readme(
    output: Path,
    docs: list[CanonicalDoc],
    root: Path,
    exported_at: str,
    index_rel: str,
) -> None:
    lines = [
        "# Xiuxian Canonical Docs Export",
        "",
        f"导出时间：`{exported_at}`",
        "",
        f"来源索引：`{index_rel}`",
        "",
        "用途：将当前 canonical 文档作为独立 Markdown 文件导入 Notion、ChatGPT Library 或其他知识库。",
        "",
        "## 导入建议",
        "",
        "- Notion：导入本目录中的编号 `.md` 文件。",
        "- ChatGPT Library：上传本目录中的编号 `.md` 文件。",
        "- `manifest.json` 供脚本化校验使用，包含原始路径、导出文件名和 SHA-256。",
        "",
        "## 文档索引",
        "",
        "| # | 主题 | 导出文件 | 原始路径 |",
        "| --- | --- | --- | --- |",
    ]
    for doc in docs:
        source_rel = doc.source_path.relative_to(root).as_posix()
        lines.append(f"| {doc.order:02d} | {doc.topic} | [{doc.export_name}]({doc.export_name}) | `{source_rel}` |")
    output.joinpath("README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_manifest(output: Path, docs: list[CanonicalDoc], root: Path, exported_at: str, index_rel: str) -> None:
    manifest = {
        "exported_at": exported_at,
        "source_index": index_rel,
        "document_count": len(docs),
        "documents": [
            {
                "order": doc.order,
                "topic": doc.topic,
                "label": doc.label,
                "source_path": doc.source_path.relative_to(root).as_posix(),
                "export_file": doc.export_name,
                "sha256": doc.sha256,
            }
            for doc in docs
        ],
    }
    output.joinpath("manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def run() -> int:
    args = parse_args()
    root = repo_root()
    index_path = resolve_inside(root, root / args.index)
    output = prepare_output(root, args.output, args.clean)
    exported_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    index_rel = index_path.relative_to(root).as_posix()
    docs = load_canonical_docs(root, index_path)

    for doc in docs:
        output.joinpath(doc.export_name).write_text(
            exported_doc_content(doc, root, exported_at, index_rel),
            encoding="utf-8",
        )

    write_readme(output, docs, root, exported_at, index_rel)
    write_manifest(output, docs, root, exported_at, index_rel)

    print(f"Exported {len(docs)} canonical docs to {output}")
    print(f"Index: {output / 'README.md'}")
    print(f"Manifest: {output / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
