#!/usr/bin/env python3
"""Export and import xiuxian design docs for ChatGPT Library round-trips."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DEFAULT_SOURCE = "docs/xiuxian_design_docs"
DEFAULT_OUTPUT = "outputs/xiuxian-design-docs-chatgpt"
MARKER_FILE = ".xiuxian-design-docs-chatgpt-export"
EXPORT_KIND = "xiuxian_design_docs_chatgpt_flat_v1"
FLAT_INDEX = "INDEX_ChatGPT扁平索引.md"
GENERATED_MARKDOWN = {"README.md", FLAT_INDEX}


@dataclass(frozen=True)
class DesignDoc:
    order: int
    source_path: Path
    source_rel: str
    package_rel: str
    export_file: str
    title: str
    section: str
    source_sha256: str


@dataclass(frozen=True)
class ImportCandidate:
    export_file: str
    source_rel: str
    source_path: Path
    status: str
    reason: str
    current_sha256: str | None
    exported_source_sha256: str | None
    body: str


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_text(text: str) -> str:
    return sha256_bytes(text.encode("utf-8"))


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def normalize_body(text: str) -> str:
    return text.rstrip() + "\n"


def resolve_repo_path(root: Path, path_arg: str) -> Path:
    path = Path(path_arg)
    if not path.is_absolute():
        path = root / path
    return path.resolve()


def ensure_inside(base: Path, candidate: Path) -> Path:
    base_resolved = base.resolve()
    candidate_resolved = candidate.resolve()
    try:
        candidate_resolved.relative_to(base_resolved)
    except ValueError as exc:
        raise ValueError(f"Path escapes allowed base: {candidate}") from exc
    return candidate_resolved


def natural_key(text: str) -> list[int | str]:
    parts = re.split(r"(\d+)", text)
    return [int(part) if part.isdigit() else part for part in parts]


def source_sort_key(path: Path, source_dir: Path) -> tuple[int, list[int | str]]:
    rel = path.relative_to(source_dir).as_posix()
    if rel == "README.md":
        group = 0
    elif rel.startswith("00_INDEX/"):
        group = 1
    else:
        group = 2
    return (group, natural_key(rel))


def first_heading(text: str, fallback: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return fallback


def section_name(package_rel: str) -> str:
    parts = Path(package_rel).parts
    if package_rel == "README.md":
        return "包入口"
    if parts:
        return parts[0]
    return "未分组"


def flat_filename(order: int, package_rel: str) -> str:
    flat = package_rel.replace("/", "__")
    flat = re.sub(r'[\\:*?"<>|]+', "-", flat)
    flat = re.sub(r"\s+", "_", flat)
    return f"{order:03d}__{flat}"


def load_design_docs(root: Path, source_dir: Path) -> list[DesignDoc]:
    docs: list[DesignDoc] = []
    files = [
        path
        for path in source_dir.rglob("*.md")
        if path.is_file()
        and not any(part.startswith(".") for part in path.relative_to(source_dir).parts)
    ]
    files.sort(key=lambda path: source_sort_key(path, source_dir))

    for order, source_path in enumerate(files, start=1):
        body = read_text(source_path)
        package_rel = source_path.relative_to(source_dir).as_posix()
        source_rel = source_path.relative_to(root).as_posix()
        docs.append(
            DesignDoc(
                order=order,
                source_path=source_path,
                source_rel=source_rel,
                package_rel=package_rel,
                export_file=flat_filename(order, package_rel),
                title=first_heading(body, source_path.stem),
                section=section_name(package_rel),
                source_sha256=sha256_text(normalize_body(body)),
            )
        )
    if not docs:
        raise RuntimeError(f"No Markdown design docs found in {source_dir}")
    return docs


def prepare_output(output: Path, clean: bool) -> None:
    if clean and output.exists():
        marker = output / MARKER_FILE
        is_empty = output.is_dir() and not any(output.iterdir())
        if not is_empty and not marker.is_file():
            raise ValueError(f"Refusing to clean unmarked non-empty directory: {output}")
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / MARKER_FILE).write_text(
        "generated by scripts/sync_design_docs_chatgpt.py\n",
        encoding="utf-8",
    )


def yaml_json(value: str | int) -> str:
    return json.dumps(value, ensure_ascii=False)


def exported_doc_text(doc: DesignDoc, exported_at: str) -> str:
    body = normalize_body(read_text(doc.source_path))
    header = "\n".join(
        [
            "---",
            f"xiuxian_export: {yaml_json(EXPORT_KIND)}",
            f"export_id: {yaml_json(f'{doc.order:03d}')}",
            f"source_path: {yaml_json(doc.source_rel)}",
            f"package_path: {yaml_json(doc.package_rel)}",
            f"source_sha256: {yaml_json(doc.source_sha256)}",
            f"exported_at: {yaml_json(exported_at)}",
            "---",
            "",
        ]
    )
    return header + body


def write_readme(output: Path, docs: list[DesignDoc], exported_at: str, source_rel: str) -> None:
    lines = [
        "# 修仙轮回沙盒｜ChatGPT Library 扁平导出包",
        "",
        f"导出时间：`{exported_at}`",
        "",
        f"本地来源：`{source_rel}`",
        "",
        "用途：把多级目录的正式设计文档包整理成 ChatGPT Library 可索引的扁平 Markdown 文件。",
        "",
        "## 上传到 ChatGPT Library",
        "",
        "1. 上传本目录中的编号 `.md` 文件。",
        f"2. 建议同时上传 `{FLAT_INDEX}`，让 Web 端能按原目录理解扁平文件。",
        "3. `manifest.json` 主要供本地回合并脚本校验使用，可以留在本地，不必上传。",
        "",
        "## 从 ChatGPT Web 回合并",
        "",
        "1. 在 Web 端修改文档时，尽量保留每个编号文档顶部的 YAML metadata。",
        "2. 下载 Web 端修改后的 Markdown 文件到本地某个目录。",
        "3. 先运行 `python3 scripts/sync_design_docs_chatgpt.py plan-import --input <下载目录>` 查看将要写回的文件。",
        "4. 确认后运行 `python3 scripts/sync_design_docs_chatgpt.py import --input <下载目录>` 写回 `docs/xiuxian_design_docs`。",
        "",
        "## 文档索引",
        "",
        "| # | 原目录 | 标题 | 扁平文件 | 本地源路径 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for doc in docs:
        lines.append(
            f"| {doc.order:03d} | `{doc.section}` | {doc.title} | "
            f"[{doc.export_file}]({doc.export_file}) | `{doc.source_rel}` |"
        )
    output.joinpath("README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_flat_index(output: Path, docs: list[DesignDoc], exported_at: str, source_rel: str) -> None:
    lines = [
        "# INDEX｜ChatGPT Library 扁平索引",
        "",
        f"导出时间：`{exported_at}`",
        "",
        f"本地来源：`{source_rel}`",
        "",
        "本文是 Web Library 侧入口。由于 ChatGPT Library 不保留本地目录层级，本索引用“扁平文件名”和“本地源路径”恢复原文档包结构。",
        "",
        "## 使用口径",
        "",
        "1. 以 `docs/xiuxian_design_docs` 的当前设计结论为准。",
        "2. 在 Web 端修订正文时，优先修改对应编号文档，不把设计结论只写进本索引。",
        "3. 下载回本地后，通过 `scripts/sync_design_docs_chatgpt.py` 的 `plan-import` 和 `import` 子命令回写。",
        "",
    ]

    current_section = None
    for doc in docs:
        if doc.section != current_section:
            if current_section is not None:
                lines.append("")
            current_section = doc.section
            lines.extend(
                [
                    f"## {current_section}",
                    "",
                    "| # | 标题 | 扁平文件 | 本地包内路径 |",
                    "| --- | --- | --- | --- |",
                ]
            )
        lines.append(
            f"| {doc.order:03d} | {doc.title} | [{doc.export_file}]({doc.export_file}) | "
            f"`{doc.package_rel}` |"
        )
    output.joinpath(FLAT_INDEX).write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_manifest(output: Path, docs: list[DesignDoc], exported_at: str, source_rel: str) -> None:
    manifest = {
        "schema_version": 1,
        "kind": EXPORT_KIND,
        "exported_at": exported_at,
        "source_root": source_rel,
        "document_count": len(docs),
        "generated_markdown": sorted(GENERATED_MARKDOWN),
        "documents": [
            {
                "order": doc.order,
                "title": doc.title,
                "section": doc.section,
                "source_path": doc.source_rel,
                "package_path": doc.package_rel,
                "export_file": doc.export_file,
                "source_sha256": doc.source_sha256,
            }
            for doc in docs
        ],
    }
    output.joinpath("manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def command_export(args: argparse.Namespace) -> int:
    root = repo_root()
    source_dir = ensure_inside(root, resolve_repo_path(root, args.source))
    output = resolve_repo_path(root, args.output)
    docs = load_design_docs(root, source_dir)
    exported_at = utc_now()
    source_rel = source_dir.relative_to(root).as_posix()

    prepare_output(output, args.clean)
    for doc in docs:
        output.joinpath(doc.export_file).write_text(
            exported_doc_text(doc, exported_at),
            encoding="utf-8",
        )
    write_readme(output, docs, exported_at, source_rel)
    write_flat_index(output, docs, exported_at, source_rel)
    write_manifest(output, docs, exported_at, source_rel)

    print(f"Exported {len(docs)} design docs to {output}")
    print(f"Upload index: {output / FLAT_INDEX}")
    print(f"Manifest: {output / 'manifest.json'}")
    return 0


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        return {}, normalize_body(text)
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}, normalize_body(text)

    raw = text[4:end]
    meta: dict[str, Any] = {}
    for line in raw.splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        try:
            meta[key] = json.loads(value)
        except json.JSONDecodeError:
            meta[key] = value.strip("'\"")

    body = text[end + len("\n---\n") :]
    if meta.get("xiuxian_export") == EXPORT_KIND:
        return meta, normalize_body(body)
    return {}, normalize_body(text)


def load_manifest(manifest_path: Path | None) -> dict[str, dict[str, Any]]:
    if manifest_path is None or not manifest_path.is_file():
        return {}
    data = json.loads(read_text(manifest_path))
    if data.get("kind") != EXPORT_KIND:
        raise ValueError(f"Unsupported manifest kind: {manifest_path}")
    return {entry["export_file"]: entry for entry in data.get("documents", [])}


def default_manifest_path(root: Path, input_dir: Path) -> Path | None:
    direct = input_dir / "manifest.json"
    if direct.is_file():
        return direct
    previous = root / DEFAULT_OUTPUT / "manifest.json"
    if previous.is_file():
        return previous
    return None


def candidate_source_path(root: Path, source_dir: Path, source_rel: str) -> Path:
    path = resolve_repo_path(root, source_rel)
    ensure_inside(source_dir, path)
    return path


def collect_import_candidates(
    root: Path,
    source_dir: Path,
    input_dir: Path,
    manifest_entries: dict[str, dict[str, Any]],
) -> tuple[list[ImportCandidate], list[str]]:
    candidates: list[ImportCandidate] = []
    skipped: list[str] = []

    for path in sorted(input_dir.glob("*.md"), key=lambda p: natural_key(p.name)):
        if path.name in GENERATED_MARKDOWN:
            continue
        text = read_text(path)
        meta, body = parse_frontmatter(text)
        manifest_entry = manifest_entries.get(path.name, {})
        source_rel = str(meta.get("source_path") or manifest_entry.get("source_path") or "")
        exported_source_sha = str(meta.get("source_sha256") or manifest_entry.get("source_sha256") or "")
        if not source_rel:
            skipped.append(f"{path.name}: missing source_path metadata and manifest entry")
            continue

        try:
            source_path = candidate_source_path(root, source_dir, source_rel)
        except ValueError as exc:
            skipped.append(f"{path.name}: {exc}")
            continue

        if not source_path.is_file():
            candidates.append(
                ImportCandidate(
                    export_file=path.name,
                    source_rel=source_rel,
                    source_path=source_path,
                    status="blocked",
                    reason="source file is missing",
                    current_sha256=None,
                    exported_source_sha256=exported_source_sha or None,
                    body=body,
                )
            )
            continue

        current_body = normalize_body(read_text(source_path))
        current_sha = sha256_text(current_body)
        incoming_sha = sha256_text(body)
        if incoming_sha == current_sha:
            status = "unchanged"
            reason = "same as local source"
        elif exported_source_sha and current_sha != exported_source_sha:
            status = "source_drift"
            reason = "local source changed after export"
        else:
            status = "changed"
            reason = "ready to write back"

        candidates.append(
            ImportCandidate(
                export_file=path.name,
                source_rel=source_rel,
                source_path=source_path,
                status=status,
                reason=reason,
                current_sha256=current_sha,
                exported_source_sha256=exported_source_sha or None,
                body=body,
            )
        )

    return candidates, skipped


def print_import_plan(candidates: list[ImportCandidate], skipped: list[str]) -> None:
    counts: dict[str, int] = {}
    for candidate in candidates:
        counts[candidate.status] = counts.get(candidate.status, 0) + 1

    if counts:
        summary = ", ".join(f"{status}={count}" for status, count in sorted(counts.items()))
    else:
        summary = "no importable markdown files"
    print(f"Import plan: {summary}")

    for candidate in candidates:
        print(
            f"- [{candidate.status}] {candidate.export_file} -> "
            f"{candidate.source_rel} ({candidate.reason})"
        )

    if skipped:
        print("Skipped files:")
        for item in skipped:
            print(f"- {item}")


def plan_from_args(args: argparse.Namespace) -> tuple[list[ImportCandidate], list[str]]:
    root = repo_root()
    source_dir = ensure_inside(root, resolve_repo_path(root, args.source))
    input_dir = resolve_repo_path(root, args.input)
    if not input_dir.is_dir():
        raise NotADirectoryError(f"Input directory not found: {input_dir}")

    manifest_path = (
        resolve_repo_path(root, args.manifest)
        if getattr(args, "manifest", None)
        else default_manifest_path(root, input_dir)
    )
    manifest_entries = load_manifest(manifest_path)
    return collect_import_candidates(root, source_dir, input_dir, manifest_entries)


def command_plan_import(args: argparse.Namespace) -> int:
    candidates, skipped = plan_from_args(args)
    print_import_plan(candidates, skipped)
    return 0


def command_import(args: argparse.Namespace) -> int:
    candidates, skipped = plan_from_args(args)
    print_import_plan(candidates, skipped)

    blocked = [
        candidate
        for candidate in candidates
        if candidate.status == "source_drift" and not args.allow_source_drift
    ] + [candidate for candidate in candidates if candidate.status == "blocked"]
    if blocked:
        print("Import blocked. Resolve blocked/source_drift files or rerun with --allow-source-drift.")
        return 1

    applied = 0
    for candidate in candidates:
        if candidate.status == "changed" or (
            candidate.status == "source_drift" and args.allow_source_drift
        ):
            candidate.source_path.write_text(candidate.body, encoding="utf-8")
            applied += 1

    print(f"Imported {applied} changed file(s).")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Round-trip docs/xiuxian_design_docs with ChatGPT Library by exporting "
            "flat Markdown files and importing edited downloads."
        )
    )
    subparsers = parser.add_subparsers(dest="command")

    export_parser = subparsers.add_parser("export", help="Export design docs into a flat upload directory.")
    export_parser.add_argument("--source", default=DEFAULT_SOURCE, help=f"Default: {DEFAULT_SOURCE}")
    export_parser.add_argument("--output", default=DEFAULT_OUTPUT, help=f"Default: {DEFAULT_OUTPUT}")
    export_parser.add_argument("--clean", action="store_true", help="Clean a previous generated export first.")
    export_parser.set_defaults(func=command_export)

    plan_parser = subparsers.add_parser(
        "plan-import",
        help="Preview which downloaded flat docs would be written back.",
    )
    plan_parser.add_argument("--source", default=DEFAULT_SOURCE, help=f"Default: {DEFAULT_SOURCE}")
    plan_parser.add_argument("--input", default=DEFAULT_OUTPUT, help=f"Default: {DEFAULT_OUTPUT}")
    plan_parser.add_argument("--manifest", help="Optional manifest.json path. Defaults to input/manifest.json.")
    plan_parser.set_defaults(func=command_plan_import)

    import_parser = subparsers.add_parser("import", help="Write changed downloaded flat docs back to source files.")
    import_parser.add_argument("--source", default=DEFAULT_SOURCE, help=f"Default: {DEFAULT_SOURCE}")
    import_parser.add_argument("--input", default=DEFAULT_OUTPUT, help=f"Default: {DEFAULT_OUTPUT}")
    import_parser.add_argument("--manifest", help="Optional manifest.json path. Defaults to input/manifest.json.")
    import_parser.add_argument(
        "--allow-source-drift",
        action="store_true",
        help="Allow overwriting local source files that changed after export.",
    )
    import_parser.set_defaults(func=command_import)

    return parser


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    if not argv or (argv[0].startswith("-") and argv[0] not in {"-h", "--help"}):
        argv = ["export", *argv]
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
